### ISSUE TITLE
unable to choose the correct library

### ISSUE THREAD

**Issue by cipianpascu** [WGSExtract/WGSExtract.github.io#12]
Hi Guys,

I have sequenced my genome with Nebula Genomics and now I try to extract different files from the raw cram file.
Even if GRCH38 is imported, I can not start the process because the application is not able to correctly determine the reference genome.

![image](https://user-images.githubusercontent.com/1932486/201474067-918a0c87-c022-45d8-b060-08cfde75c1aa.png)

Please help me get through this process.

Thank you,
Ciprian

**Comment by RandyHarr** [comment]
Nebula Genomics changed their reference model, without notice, last month.  From hs38 to hs38d1.  hs38dh is a superset of hs38d1 and you can reliably select that to proceed for almost all uses.  The software has been updated in 4.41 to handle the new reference genome hs38d1 but is only released on the DEVelopers release channel in version 4.  It should be updated to Alpha release shortly. Until you upgrade to that version (or later), you will have to manually select hs38dh.
