### ISSUE TITLE
450 FTP error while downloading selected reference genome

### ISSUE THREAD

**Issue by georggf** [WGSExtract/WGSExtract.github.io#13]
Downloading and Processing hs38d1 No Alt + 2385 hs38d1 Decoys (1K; @US NIH)
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
 99 --   833M     0     1     1     0  0:07:20  0:09:24 --:--:-- 1938k      curl: (18) server did not report OK, got 450
Warning: Problem : FTP error. Will retry in 1 seconds. 5 retries left.
Throwing away 874637925 bytes

I've got this continuous error
Downloading  hs38 Chr rCRS 195 SN was ok.

My cram is newest Nebula Genomics 30 wgs approximately 120 Gb size.

SUCCEDED with Library.bat #13 genome.
Other guy reported success with manual wget --continue flag

**Comment by RandyHarr** [comment]
Sorry you are having problems.  We have seen this occasionally when you try and use a wireless connection for large files. Also, some ISPs in some locations have restrictions with access to certain servers or large files. A reference model is the largest file WGS Extract ever downloads.  But it is only 1GB compared to your very large CRAM.

All the hsxxx models are available from two sources.  You select the source by the program setting (first tab) of either NIH or EBI. Sometimes people may have a problem accessing one server or the other but not both. NIH is the NIH.gov server in USA.  EBI is normally the EBI server in the UK.  You had selected NIH (seen in the log above).  So change your setting to EBI and try again.  (Note: in this particular case, EBI does not have the more unique model on their server.  So we placed it on an MS Onedrive disk (where the WGS Extract program is installed from) as the second option.)
 
Worst case, but it is not easy, you can download the reference model yourself and place it in the WGS Extract installation reference/genomes/ folder.  Look at the file genomes.csv (comma separated spreadsheet) there and you will find the two URLs for hs38d1.  Download and name it as shown there (hs38d1.fna.gz).  You will then have to initiate a BASH shell (cygwin64/cygstart.bat on Windows, Terminal on MacOS and Linux), change directory to that folder:
  cd ~/WGSExtractv4/reference/genomes/    and then run the following command: 
  ~/WGSExtractv4/scripts/process_refgenomes.sh hs38d1.fna.gz
 In both cases, change ~/WGSExtractv4 to the path of where ever your installation is. (If, on the off chance you relocated your reference library in the settings, adjust the first path to that for the cd command and make sure you have put the downloaded file there before executing the second command.)
 
Hopefully, you just need to change the setting to EBI and it will work. Sorry the manual is not yet updated to explain this all yet. Let me know the result so we can close the issue if resolved.

**Comment by RandyHarr** [comment]
We have, as of Jan 15, added more robustness to the Curl command invocation.  The biggest is finding and removing all older ftp links and changing to https.  This seems to get rid of all (most) HTTP 450 errors.  FTP has been officially retired by all the browsers and many servers.  Everything has switched to https. So I will mark this closed. Let us know if you continue to have problems with the next release (hopefully out within the next week).
