### ISSUE TITLE
1240K?

### ISSUE THREAD

**Issue by ulfing** [WGSExtract/WGSExtract.github.io#14]
Hi Randy, not really an issue, more of a question really. In the WGSExtract manual there's a screenshot of v4 interface with convert to Reich Labs option (in the RAW section). However I can find no such option in the actual WGSExtract I have on my computer, and it is also supposed to be v4. Do I have the wrong version?

**Comment by RandyHarr** [comment]
No. One of the rare cases where I updated the documentation before the software. The buttons appear in the DEBUG mode on the Alpha and Developer release. Got hung up releasing that update with other issues that are more pressing.
