### ISSUE TITLE
Error downloading `hg19_WGSE.fa.gz`.

### ISSUE THREAD

**Issue by Fluvian** [WGSExtract/WGSExtract.github.io#17]
I saw the earlier issue about the OneDrive being messed up. Just posting this to see if someone could post an updated link to `hg19_WGSE.fa.gz` while a fix is being worked on, it is the one listed as "hg37 (rCRS; WGSE v1; BAD)". Thank you in advance.

**Comment by RandyHarr** [comment]
Still resolving as we have to check and patch the old "latest-release" files, their pointers and the zips.  But the seed-genomes.csv file is posted and updated (https://raw.githubusercontent.com/WGSExtract/WGSExtract-Dev/master/seed_genomes.csv). It can be used to replace your current file in the program/ folder. (Depending on your version, it may need to go in the reference/ folder.)  

To avoid this ever happening again, we are putting any embedded links on the wgse.io server that will redirect to the appropriate cloud server source.  Making it easy for us to update one file in one place when needed. 

Here are the 9 links in seed-genomes.csv that are hosted on our cloud server (and are reflected in the new seed-genomes.csv file):
https://get.wgse.io/GRCh38_Verily_v1.genome.fa.gz  
https://get.wgse.io/hg19_complete.fasta.gz  
https://get.wgse.io/hg19_WGSE.fa.gz  
https://get.wgse.io/hs.build37.1.fa.gz  
https://get.wgse.io/hs37.fa.gz  
https://get.wgse.io/hs38.fa.gz  
https://get.wgse.io/hs38d1.fna.gz  
https://get.wgse.io/hs38d1a.fna.gz  
https://get.wgse.io/hs38d1s.fa.gz
