### ISSUE TITLE
Extracted files are useless

### ISSUE THREAD

**Issue by IssaEgvi** [WGSExtract/WGSExtract.github.io#20]
Hi, I used the program to extract various files from Dante's BAM and couldn't get GEDMatch to accept any of them.
Errors it found were 
HTZ percentage out of range / Failed HTZ ratio test. 

More worrisome was the fact extracted 23AndMe V3 file keeps finding me hundreds of siblings on ancestry websites.
I also have extremely odd health reports on Promethease, completely different from Dante original reports.

Since GEDMatch still allows you to compare various erroneous files, I compared two unrelated genomes extracted via WGS Extract and surprise, they are also supposedly siblings.

So WGS extract is clearly doing something to my BAM and making it not reflect the original genome?? How is that even possible?
It's a simple process of clicling Extract data and selecting which formats you want... I followed the tutorial.

**Comment by RandyHarr** [comment]
Please check the consumerWGS Facebook group. This is a known issue with a batch of nonsense results that Dante Labs has returned from a particular MGI DNB T7 run. Dante will have to resequence to get valid results. We will work to add a check in a future release for this particular, arcane error that Dante has generated.

**Comment by IssaEgvi** [comment]
Dear Mr Randy H,

The group you recommended isn't accepting my request for 5 days now.
And Dante is asking me to prove there's anything wrong with my kits.
So I am afraid none of this is very helpful but thank you for tying.

Best regards,
Marina C

**Comment by RandyHarr** [comment]
Resolved. Group membership accepted.
