### ISSUE TITLE
Dev WGSExtractv4 Installation Issue

### ISSUE THREAD

**Issue by aantix** [WGSExtract/WGSExtract.github.io#23]
I'm running macOS Sonoma 14.0.

I am running the dev latest build, as that is the only one that supports Sonoma. 

I execute `./Install_macos.command`

All dependencies appear to install correctly.   I get to this point

```
...  Started installing WGS Extract Program v45 ...
############################################################################################################################################################################################################################################## 100.0%
ERROR: program.zip
program.zip
Open ERROR: Cannot open the file as [zip] archive


ERRORS:
Is not archive
*** ERROR: WGSExtractv4 directory not created when expanding
           program.zip during package program install
```

The script is trying to download the app at 

https://get.wgse.io/WGSExtract-v45_30Oct2023_program.zip but that zip file doesn't exist.

Is it possible to get the build posted?

**Comment by RandyHarr** [comment]
Go ahead and retry. It appears one of the pre-release pointers from a test development release overwrote a file on the release server.  Should be fixed now.  There is no v45_30Oct2023 release of the program package.  Only v44.3_30Oct2023. Apologies for the mix-up.

**Comment by aantix** [comment]
No worries @RandyHarr.  Thank-you for all of your hard work on WGS.
