### ISSUE TITLE
wakepy import set_keepawake, unset_keepawake   # Ugly....

### ISSUE THREAD

**Issue by DogCatSpace** [WGSExtract/WGSExtract.github.io#25]
Hi,

Excited to use WGSE but ran into a problem.  I installed Dev(eloper) v4+)successfully on a W10 machine but cannot get it to run.  The error message is below.  What is happening?  Error message is below: 

Starting WGS Extract on cygwin64 ...
Traceback (most recent call last):
  File "E:\WGSExtract-Dev45_30Mar2024_installer\WGSExtractv4\program\wgsextract.py", line 109, in <module>
    from mainwindow import set_output_path, set_BAM_file
  File "E:\WGSExtract-Dev45_30Mar2024_installer\WGSExtractv4\program\mainwindow.py", line 57, in <module>
    from commandprocessor import run_bash_script
  File "E:\WGSExtract-Dev45_30Mar2024_installer\WGSExtractv4\program\commandprocessor.py", line 28, in <module>
    from wakepy import set_keepawake, unset_keepawake   # Ugly, but cannot import on Ubuntu aparently
ImportError: cannot import name 'set_keepawake' from 'wakepy' (E:\WGSExtract-Dev45_30Mar2024_installer\WGSExtractv4\python\lib\site-packages\wakepy\__init__.py)
Press any key to continue . . .

**Comment by RandyHarr** [comment]
Rerun the installer.  We were able to finally push out a release update to fix this issue that cropped up on all platforms.  There had been a fix on the main website page.  But all the releases are now patched. This only affected new installations or installations that did an update via the installer.

**Comment by DogCatSpace** [comment]
That was quick! and thanks.  It worked!  One more question.  With Nebula, should I use the "Default" Ref. Library or use the CRAI file from Nebula?

**Comment by RandyHarr** [comment]
Nebula crai is fine and saves 30-60 minutes of processing on your own machine. 

Not sure what you mean default ref library for Nebula.  The tool should determine the existing ref Genome. The only time a default is chosen is if you hit the Realign button. There is no way to override the choice in that case.

**Comment by DogCatSpace** [comment]
Bravo on WGSE. As a microbiologist whom did his thesis in DNA fingerprinting in 1992, I can say this is extraordinary (that it is free is another astonishingly positive).  I am slogging through the 2022 Manual and will restrict my questions to just two. 

1. I see CombinedKit "can only be used at at GEDMatch..." If this is still correct, and with a RAW from Nebula, what is appropriate (23&Me, etc.) for Promethease? Safe to assume it is 23&Me version what?

2.  It seems VCF files are best for InDel; Which Nebula input should I start with to charge-forward on InDel within WGS E?  The nebula VCF file is ~450 MB and seems incompatible with Promethease analysis.

**Comment by DogCatSpace** [comment]
Thanks, importantly the 2022 WGS Extract Manual (pg 25) states "CombinedKit can only be used at [GEDMatch] and [Geneanet].   Does this mean that CombinedKit is likely to be accurate wherever used, but may not be accepted on some platforms?

**Comment by RandyHarr** [comment]
I will have to read that section of the manual for context. It seems that statement on limitations only applies to genetic genealogy sites. 

Many sites are only setup to read a normal, single microarray result file of around 600k entries. The CombinedKit is over 2 million entries. A chip microarray is usually limited to testing around 1 million sites.
