### ISSUE TITLE
Providing a container installing and running WGS Extract.

### ISSUE THREAD

**Issue by junaruga** [WGSExtract/WGSExtract.github.io#26]
Hi, thanks for providing this app. I found this app because this app is introduced by [this page](https://www.geneticlifehacks.com/convert-whole-genome-file/).

A challenge is that I am using [Fedora Linux](https://fedoraproject.org/) as my desktop environment, not Ubuntu. But I want to use this app.

I would like to see an option to install and run this WGS Extract app as a container (or called docker) using a container registry such as BioContainer[1], Quay.io[2], etc. I think this way may give users a much easier experience with installing and using this app. You can make this app available on wider platforms in this way. I would appreciate it if you would consider this option.

* [1] https://biocontainers.pro/
* [2] https://quay.io/

**Comment by RandyHarr** [comment]
Thank you for the suggestion.  Please read the tail end of the home page here.  You can install on other Linux's using the Linux Installer based on micromamba.  Our experimentation with containers has shown it is not a viable platform.  Each of the 30+ bioinformatic tools requires a container. The the interprocess communication overhead of that with 250 GB+ size streams is very slow.  If you find a solution, let us know.

**Comment by junaruga** [comment]
@RandyHarr Thank you for your reply.

> Each of the 30+ bioinformatic tools requires a container.

Did you mean 30+ containers are required to run WGS Extract? I think only one container is required to run WGS Extract. You can contain WGS Extract app with the 30+ dependent bioinformatic tools in one container.

**Comment by junaruga** [comment]
By the way, I think the most popular and my favorite container-based app is [Flatpak](https://flatpak.org/)-based app, and store the app at [Flathub](https://flathub.org/). The document is [here](https://docs.flatpak.org/en/latest/index.html).

**Comment by junaruga** [comment]
> Please read the tail end of the home page here. You can install on other Linux's using the Linux Installer based on micromamba.

Thank you for the info!
