### ISSUE TITLE
Apple M1 issue

### ISSUE THREAD

**Issue by iammickeymac** [WGSExtract/WGSExtract.github.io#3]
I recently upgraded to an M1 Mac mini and today attempted to re-run the cram-to bam utility on my Nebula 100x file and received this error:

michaelmccarthy@Michaels-Mac-mini-4 /Users %
 samtools view -bho NB2J6P68.bam -@ 4 -m 2G -T GCA*.fna.gz NB2J6P68.cram
zsh: no matches found: GCA*.fna.gz
michaelmccarthy@Michaels-Mac-mini-4 /Users % samtools view -bho NB2J6P68.bam -@ 4 -m 2G -T GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz NB2J6P68.cram
dyld: Library not loaded: /opt/local/lib/libncurses.6.dylib
  Referenced from: /opt/local/bin/samtools
  Reason: no suitable image found.  Did find:
	/opt/local/lib/libncurses.6.dylib: mach-o, but wrong architecture
	/opt/local/lib/libncurses.6.dylib: stat() failed with errno=1
	/opt/local/lib/libncurses.6.dylib: mach-o, but wrong architecture
zsh: abort      samtools view -bho NB2J6P68.bam -@ 4 -m 2G -T  NB2J6P68.cram

Any ideas?
Thank you, Michael

**Comment by RandyHarr** [comment]
It looks like the M1 system emulator is not accepting the libncurses library in macports.  Maybe try reinstalling MacPorts and see if this clears up the issue.  Otherwise, it is something that will have to be investigated with MacPorts and those doing the Samtools ports and release therein.  Not sure any of us will have an M1 architecture machine for awhile yet to be able to test out the Apple compatability issues.  Not to mention it is so new that am sure Apple and MacOSX is having a "boatload" of problems like this as well.

**Comment by iammickeymac** [comment]
Thanks Randy,
I reinstalled Macports, no change and posted my problem here. Will keep trying and maybe someone out there is experimenting.
Michael

**Comment by RandyHarr** [comment]
Seems even the developers are having issues where universal builds are not drawing the correct universal libraries. See http://mac-os-forge.2317878.n4.nabble.com/61750-cmake-port-installation-failure-Big-Sur-AArch64-M1-td407902.html

**Comment by iammickeymac** [comment]
That makes sense!
I will uninstall the apps and wait for a fix.
Thank you for help with the Gedmatch file.
Michael

**Comment by RandyHarr** [comment]
We presume you are using the native MacOSX terminal.  So not sure this applies. But maybe setting the build_arch arm64 in macports.conf will help?  See https://trac.macports.org/wiki/BigSurProblems . As we do not have the M1 nor BigSur (MaxOS 11), we cannot really submit a bug report there.  But if you continue to have issues, or even now, I would urge you to submit a report there about this problem.  You do not have to mention WGS Extract; just the samtools failure from your scripts as given here.

**Comment by iammickeymac** [comment]
Thanks Randy.
I updated Xcode yesterday and I believe that Apple will be shortly be sending out an update to Big Sur.
I will give it another attempt after upgrading.
Michael

**Comment by RandyHarr** [comment]
Any progress with M1?  Did MacPorts finally iron itself out on this platform?

**Comment by iammickeymac** [comment]
Unfortunately no change.
I will be repurposing my old intel MacBook when I can take some time off.
Vaccination frenzy has all hands on deck for the immediate future 🙄
I will retry after each update to the Mac OS and keep you posted of any change.
Michael

**Comment by RandyHarr** [comment]
We have verified this is now resolved. As Macports cannot update itself, you do have to uninstall and reinstall Macports. M1 is verified fully operational for the tool here.
