### ISSUE TITLE
unable to extract the zip file

### ISSUE THREAD

**Issue by jadenfox9** [WGSExtract/WGSExtract.github.io#4]
The zip file (WGSExtractBetav2b_full.zip) downloads fine from google drive,
https://drive.google.com/u/0/uc?id=1F_vclX1FPibnBdSyQ25OXPHzJUl6dwcJ&export=download
has 4.82gb

but it encounters errors on extraction using a variety of different apps 
(Mac 10.15.7)

**Comment by RandyHarr** [comment]
Jaden, thank you for finding us here to open an inquiry.  There is no question the MacOS platform has been a struggle for tools like ours over the last 6 months as Apple tightens security around non-App store released products on their platform.  Killing the researcher environment that Unix and the Mac in Bioinformatics has long enjoyed.  Zip files with binary blobs, compiled Applescripts, use of BASH scripting language and such are all being constantly blocked in new and different ways.

Could you provide any more details as to your issue?  In most cases (on Catalina especially), MacOS will automatically unzip the files and scan them. Deciding whether to jail the directory depending on what it finds.  So hopefully, that is not the issue.  Next, even though it puts the folder in Downloads, it cannot be executed from there.  As described in the manual, it cannot be in Downloads or Documents.  Often best to simply move it to your home directory itself. They have now separated the file system (hidden to you for the most part) between the system area and user space.  And disallow system space modifications -- only allowing their OS there to ease updates and improve security (in their view). Make sure to do the Mac overlay onto your main Zip content.  You may have to allow Security & Privacy (Privacy) tab access to the Start_MacOSX, Install_MacOSX and Uninstall_MacOSX scripts after moving all the files to your home folder; say like ~/WGSEv2. (Use Apple-Key H in the GUI to get to your home; something they hide in Finder in general.)  You set the permission by navigating to the files under the Privacy Tabs Full Access option.

I Just went through the process from download to install on a clean MacOSX Catalina installation in this way.

**Comment by jadenfox9** [comment]
Hi Randy,

Not much else to say, it acted as if the file is corrupted.  Clicking on the zip file (still in my downloads folder) to uncompress gives you me error:
<img width="396" alt="Screen Shot 2021-02-24 at 9 07 21 AM" src="https://user-images.githubusercontent.com/79554853/109015362-9f799380-76e7-11eb-958a-f205016dbd60.png">

So I tried to uncompress the same file with another unzipper and got a slightly different error:
<img width="448" alt="Screen Shot 2021-02-24 at 9 12 22 AM" src="https://user-images.githubusercontent.com/79554853/109015391-a99b9200-76e7-11eb-94ee-43d4a2b79ca0.png">

It's NOT a Security & Privacy issue, those are easy to resolve

**Comment by RandyHarr** [comment]
Odd. My test earlier was by clicking on the link. Although more so on the Win10 systems, the Google SPAM system can be an issue for some that have download managers.  They get the HTML code to the link instead of the download file itself.  We just recently moved the release to Google Drive but it appears this may be a mistake. Have found no way around their SPAM system for >100MB files even though we pay for the service.  How did you do the download?  Via Safari?

**Comment by jadenfox9** [comment]
I downloaded it in Chrome (up-to-date) but let me try Safari...

**Comment by RandyHarr** [comment]
That would be odd that Google Chrome on a Mac cannot download from Google Drive ...

**Comment by jadenfox9** [comment]
I just tried with Firefox, that also failed...

But surprise, surprise... SAFARI WORKED!  :)

I have the files now!
<img width="392" alt="Screen Shot 2021-02-24 at 10 18 52 PM" src="https://user-images.githubusercontent.com/79554853/109022344-4fea9600-76ee-11eb-80a4-dde3b02447ef.png">

**Comment by RandyHarr** [comment]
Glad to hear. I added a note to the home page that should appear shortly.

**Comment by RandyHarr** [comment]
Since you opened a new issue in this same but continuing topic, I am closing this one.
