### ISSUE TITLE
Mac install error- No such file or directory

### ISSUE THREAD

**Issue by jadenfox9** [WGSExtract/WGSExtract.github.io#5]
Something is not right, but I can't figure it out.

-I downloaded WGSExtract and the mac patch.
-I copied the 6 files from the Mac patch to the WGSExtract folder (in Documents folder)

<img width="331" alt="Screen Shot 2021-02-27 at 11 20 36 AM" src="https://user-images.githubusercontent.com/79554853/109375232-da4d1880-78ed-11eb-954e-520b7eb26856.png">

- I launch "Install_MacOSX.app"
- enter password in terminal window and get this error message:
/bin/sh: /private/var/folders/j3/_hl0zcvx28q4yx7r89256y3w0000gp/T/AppTranslocation/A7D47342-A294-4A0E-86A8-231B511E608A/d/Install_MacOSX.sh: **No such file or directory**

Here is what I see in the terminal window:
`Last login: Sat Feb 27 11:11:00 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Jadens-MBP16:~ jadenfox2$ sudo -H  /bin/sh /private/var/folders/j3/_hl0zcvx28q4yx7r89256y3w0000gp/T/AppTranslocation/A7D47342-A294-4A0E-86A8-231B511E608A/d/Install_MacOSX.sh; exit
Password:
/bin/sh: /private/var/folders/j3/_hl0zcvx28q4yx7r89256y3w0000gp/T/AppTranslocation/A7D47342-A294-4A0E-86A8-231B511E608A/d/Install_MacOSX.sh: **No such file or directory**
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

Suggestions?

**Comment by RandyHarr** [comment]
I have made some comments about this in the manual and here. The "translocation" in that is path is the key. Apple has jailed the compiled applescript programs. You can either (a) run the bash scripts directly in a terminal, (b) recompile the applescript locally on your machine (you may have to extract the source from the .app folder) or (c) navigate down into the .app folder to find the compiled applescript program and click it directly.

**Comment by jadenfox9** [comment]
Ok, I need to be honest, I can't make sense of any of this.
I'm NOT techie.  I do have the "WGSExtract" in my home folder, finally

**(a)  run the bash scripts directly in a terminal**
if you mean this thing...  /usr/local/bin/python3 ~/WGSExtract/programs/wgsextract/wgsextract.py
when I run it, I get this:
_Jadens-MBP16:~ jadenfox2$ /usr/local/bin/python3 ~/WGSExtract/programs/wgsextract/wgsextract.py
-bash: /usr/local/bin/python3: No such file or directory
Jadens-MBP16:~ jadenfox2$_ 

I can even manually open this file:  /WGSExtract/programs/wgsextract/wgsextract.py
but it's just code, not sure what to do from there.

**(b) recompile the applescript**
I haven't the foggiest clue what this means

**(c) navigate down into the .app folder to find the compiled applescript program and click it directly.**
I can find no ".app" folder or anything that resembles this to find the applescript file

I've looked at the manual over and over...

**To Start The (Installer) Program via the command line: 
In the Terminal command line window, type the following commands:**
_% cd ~/WGSExtract
% sudo -H /bin/sh Install_MacOSX.sh_

I get:

_Jadens-MBP16:~ jadenfox2$ % cd ~/WGSExtract
-bash: fg: %: no such job
Jadens-MBP16:~ jadenfox2$ % sudo -H /bin/sh Install_MacOSX.sh
-bash: fg: %: no such job
Jadens-MBP16:~ jadenfox2$_

**Comment by RandyHarr** [comment]
Sorry you are still having issues. We can likely best solve this by doing a screen share during a session with Skype, Zoom, or TeamViewer. But in case that cannot happen, here is a response to your last note above:

(a) You cannot run the Start_MacOSX script directly if you have not run the Install_MacOSX script first. You do not have a working python3 put in by the installer to run the start command.  It is reporting it cannot find that command.

(b) Look at your first post to us and the image of your directory. So the "folder" that appears with the ".app" suffix? That is what appears with the compiled applescript icon. It is not a file but a folder.

(c) You copied the prompt character that was left in in cases when the document is viewed on small screens and wraps the single line commands around. Type the commands without the pre-pended "%" sign and they should work just fine.

As a reminder, the only problem you are having is the pre-compiled Applescript executables have been "jailed" by GateKeeper using the "translocation" mechanism to isolate just that Applescript app away from the rest of the files in the release. To ersolve this, we have to become a paid developer of Apple Store to get license codes to electronically sign releases.  See [Synack Untranslocating Apps](https://www.synack.com/blog/untranslocating-apps/) for a bit of a description of the continuing issues around this.  We are looking into ways to split the distribution on Apple-only so the compiled Applescript files can be first immediately moved to the Applications folder. Our other, simpler solution, is to simply remove the Applescript click-button start and require all to use the Terminal to start the program.  Not desirable but maybe the best near term fix.

**Comment by jadenfox9** [comment]
SUCCESS!  Mostly...

I got WGS Extract to run  :)   - Weeeee!

But I only have a CRAM file not BAM.
I can find no CRAM to BAM converters for Mac OS.

Do you have any suggestions Randy?

_Sooooo close!_

**Comment by RandyHarr** [comment]
CRAM files are supported in the unreleased Alpha v3 due out soon. Sorry to say, but that will require you install that update after joining the alpha test group. We do not have the code here yet or an ability to install from here.

Closing the issue here as resolved. Will send an invite to the alpha test group separately.
